# parameters comes from https://github.com/ggerganov/whisper.cpp/blob/4ef3398e8fe0c426de038b8c3816c6791a34a5ae/examples/main/main.cpp#L135-L165
# and https://github.com/openai/whisper/blob/f82bc59f5ea234d4b97fb2860842ed38519f7e65/whisper/transcribe.py#L252-L278
whisper_ros_node:
  best_of:
    {
      type: int,
      default_value: 5,
      description: "number of candidates when sampling with non-zero temperature",
      read_only: true,
      validation: { lower_bounds<>: [1] },
    }
  beam_size :
    {
      type: int,
      default_value: 5,
      description: "number of beams in beam search, only applicable when temperature is zero",
      read_only: true,
      validation: { lower_bounds<>: [1] },
    }
  audio_buffer_length:
    {
      type: int,
      default_value: 262144,
      description: "buffer length of raw audio data (uint8)",
      read_only: true,
      validation: { lower_bounds<>: [1] },
    }
  n_threads:
    {
      type: int,
      default_value: 4,
      description: "number of threads to use during computation",
      read_only: true,
      validation: { lower_bounds<>: [1] },
    }
  n_processors:
    {
      type: int,
      default_value: 1,
      description: "number of processors to use during computation",
      read_only: true,
      validation: { lower_bounds<>: [1] },
    }
  offset_t_ms:
    {
      type: int,
      default_value: 0,
      description: "time offset in milliseconds",
      read_only: true,
      validation: { lower_bounds<>: [0] },
    }
  offset_n:
    {
      type: int,
      default_value: 0,
      description: "segment index offset",
      read_only: true,
      validation: { lower_bounds<>: [0] },
    }
  max_context:
    {
      type: int,
      default_value: -1,
      read_only: true,
      description: "maximum number of text context tokens to store",
    }
  max_len:
    {
      type: int,
      default_value: 0,
      description: "maximum segment length in characters",
      read_only: true,
      validation: { lower_bounds<>: [0] },
    }
  word_thold:
    {
      type: double,
      default_value: 0.01,
      read_only: true,
      description: "word timestamp probability threshold",
    }
  entropy_thold:
    {
      type: double,
      default_value: 2.4,
      read_only: true,
      description: "entropy threshold for decoder fail",
    }
  logprob_thold:
    {
      type: double,
      default_value: -1.0,
      read_only: true,
      description: "entropy threshold for decoder fail",
    }
  speed_up:
    {
      type: bool,
      default_value: true,
      read_only: true,
      description: "speed up audio by x2 (reduced accuracy)",
    }
  translate:
    {
      type: bool,
      default_value: false,
      read_only: true,
      description: "translate from source language to english",
    }
  diarize:
    {
      type: bool,
      default_value: false,
      read_only: true,
      description: "stereo audio diarization",
    }
  language:
    {
      type: string,
      default_value: "en",
      read_only: true,
      description: "spoken language ('auto' for auto-detect)",
    }
  prompt: { type: string, default_value: "", description: "initial prompt" }
  model_type:
    {
      type: string,
      default_value: "base.en",
      read_only: true,
      description: "type of the model",
      validation:
        {
          one_of<>:
            [
              [
                "tiny.en",
                "tiny",
                "base.en",
                "base",
                "small.en",
                "small",
                "medium.en",
                "medium",
                "large-v1",
                "large",
              ],
            ],
        },
    }
