name: BuildTest

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *
  pull_request:
    paths:
      - '**'
      - '!docs/**'
  push:
    branches:
      - master

jobs:
  build_test:
    name: BuildTest
    runs-on: ubuntu-22.04
    timeout-minutes: 180
    container:
      image: ${{ matrix.docker_image }}
    env:
      DEBIAN_FRONTEND: noninteractive
      ROS_DISTRO: ${{ matrix.rosdistro }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Humble Hawksbill (May 2022 - May 2027)
          - docker_image: rostooling/setup-ros-docker:ubuntu-jammy-ros-humble-ros-base-latest
            rosdistro: humble
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: workaround for jammy
        if: ${{ matrix.rosdistro == 'humble' }}
        run: |
          apt remove libunwind-14-dev -y
          apt install python3-nose -y
          pip uninstall nose -y
      - name: Search packages in this repository
        id: list_packages
        run: |
          echo ::set-output name=package_list::$(colcon list --names-only | sed -e ':loop; N; $!b loop; s/\n/ /g')
      - name: Show target packages
        run: |
          echo "Target packages: ${{ steps.list_packages.outputs.package_list }}"
      - uses: ros-tooling/action-ros-ci@v0.2
        with:
          package-name: whisper_ros
          target-ros2-distro: ${{ matrix.rosdistro }}
          vcs-repo-file-url: dependency.repos
          extra-cmake-args: -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
          colcon-defaults: |
            {
              "build": {
                "mixin": ["coverage-gcc", "coverage-pytest"]
              },
              "test": {
                "mixin": ["coverage-pytest"]
              }
            }
          colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/1ddb69bedfd1f04c2f000e95452f7c24a4d6176b/index.yaml
      # - uses: codecov/codecov-action@v1.2.1
      #   with:
      #     files: ros_ws/lcov/total_coverage.info,ros_ws/coveragepy/.coverage
      #     flags: unittests
      #     name: codecov-umbrella
