name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: ChatGTP explain code
        uses: OUXT-Polaris/chatgpt-github-actions@feature/review
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_pr_id: ${{ github.event.number }}
          openai_engine: "gpt-3.5-turbo" #optional
          openai_temperature: 0.5 #optional
          openai_max_tokens: 2048 #optional
          mode: review